on: [push]

name: R-CMD

jobs:
  R-CMD:
    if: (github.actor == 'kbnurlan')
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} 

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest }

    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies
        run: |
	  Rscript -e "install.packages("https://cloud.r-project.org/src/contrib/openssl_2.1.1.tar.gz", repos=NULL, type="source")"
          Rscript -e "install.packages(c('telegram.bot','readxl','gridExtra', 'tidyverse', 'grid', 'lubridate','pillar','tidyquant'))"


      - name: Create and populate .Renviron file and Run
        run: |
          echo BOT_ID="$BOT_ID" >> ~/.Renviron
          echo GIT_ID="$GIT_ID" >> ~/.Renviron
          Rscript rscript.R
          Rscript another_rscript.R
        shell: bash
